# Minimal Nav2 parameters (use defaults from Nav2)
robot_localization_node:
  ros__parameters:
    use_sim_time: true

amcl:
  ros__parameters:
    use_sim_time: true

bt_navigator:
  ros__parameters:
    use_sim_time: true

waypoint_follower:
  ros__parameters:
    use_sim_time: true

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 20.0
    simple_goal_checker:
      tolerance: 0.25

planner_server:
  ros__parameters:
    use_sim_time: true
